# Generated by Django 2.2.12 on 2020-05-25 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='apellido',
            field=models.CharField(default='DEFAULT VALUE', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='fotografia',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='nombre',
            field=models.CharField(default='DEFAULT VALUE', max_length=30),
        ),
    ]
